In [1]:
import pandas as pd

In [5]:
# Read the CSV file with the correct delimiter
df = pd.read_csv('/home/ronja/documents/studium/bi-project/data/atp_matches_till_2022_preprocessed.csv', delimiter=',', low_memory=False)

In [8]:
print(df[df['winner_id'] == 200670 & df['year'] == 2022]['winner_match_ratio'].sum())
#print(df[df['loser_id'] == some_player_id & df['year'] == some_year]['loser_match_ratio'].sum())

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [7]:
df

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year,winner_match_ratio,loser_match_ratio
0,1968-9343,Bloemfontein,Hard,64,A,1968-01-08,269,110049,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1968,0.166667,0.500000
1,1968-9343,Bloemfontein,Hard,64,A,1968-01-08,269,110049,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1968,0.333333,0.500000
2,1968-9343,Bloemfontein,Hard,64,A,1968-01-08,250,100121,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1968,0.018182,0.250000
3,1968-9343,Bloemfontein,Hard,64,A,1968-01-08,250,100121,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1968,0.036364,0.250000
4,1968-9343,Bloemfontein,Hard,64,A,1968-01-08,250,100121,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1968,0.054545,0.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1399182,2022-M-DC-2022-FLS-M-AUS-CRO-01,Davis Cup Finals SF: AUS vs CRO,Hard,2,D,2022-11-25,2,200282,NaN,NaN,...,NaN,NaN,NaN,24.0,1790.0,17.0,2105.0,2022,0.986111,1.000000
1399183,2022-M-DC-2022-FLS-M-ITA-CAN-01,Davis Cup Finals SF: ITA vs CAN,Hard,2,D,2022-11-26,1,132283,NaN,NaN,...,NaN,NaN,NaN,45.0,950.0,18.0,2075.0,2022,1.000000,0.983333
1399184,2022-M-DC-2022-FLS-M-ITA-CAN-01,Davis Cup Finals SF: ITA vs CAN,Hard,2,D,2022-11-26,2,200000,NaN,NaN,...,NaN,NaN,NaN,6.0,4195.0,23.0,1865.0,2022,0.988506,1.000000
1399185,2022-M-DC-2022-FLS-M-CAN-AUS-01,Davis Cup Finals F: CAN vs AUS,Hard,2,D,2022-11-27,1,133430,NaN,NaN,...,NaN,NaN,NaN,18.0,2075.0,95.0,592.0,2022,1.000000,1.000000
1399186,2022-M-DC-2022-FLS-M-CAN-AUS-01,Davis Cup Finals F: CAN vs AUS,Hard,2,D,2022-11-27,2,200000,NaN,NaN,...,NaN,NaN,NaN,6.0,4195.0,24.0,1790.0,2022,1.000000,1.000000